name: ihlevital

proxy:
  appserver:
    - ihlevital.local.vielhuber.de
  pma:
    - phpmyadmin-ihlevital.local.vielhuber.de

services:
  # apache + php
  appserver:
      type: php:7.2
      via: apache
      ssl: true
      webroot: .
  # sql
  database:
    type: mysql:5.7
    portforward: true
    creds:
      database: ihlevital
      #user: root
      #password: root
  # phpmyadmin
  pma:
      type: phpmyadmin:4.7
      hosts:
       - database
      #overrides:
        #services:
          #environment:
              #PMA_USER: root
              #PMA_PASSWORD: root
              #PMA_HOST: database
              #PMA_PORT: 3306

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
  composer:
    service: appserver
    description: Run composer commands
    cmd: composer --ansi
  php:
    service: appserver
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell