$convertedInputPath = 'input.png';
$convertedOutputPath = 'output.jpg';
$convertedQuality = 75;
$convertedSource = imagecreatefrompng($convertedInputPath);
$convertedTarget = imagecreatetruecolor(imagesx($convertedSource), imagesy($convertedSource));
imagefill($convertedTarget, 0, 0, imagecolorallocate($convertedTarget, 255, 255, 255));
imagealphablending($convertedTarget, true);
imagecopy($convertedTarget,$convertedSource,0,0,0,0,imagesx($convertedSource),imagesy($convertedSource));
imagedestroy($convertedSource);
imagejpeg($convertedTarget, $convertedOutputPath, $convertedQuality);
imagedestroy($convertedTarget);
$pdf->Image($convertedOutputPath, 65, 65, 80, 0);