$img->image_height = 100;
$img->image_width = $img->image_height * M_E;
$img->perturbation = 0.50;
$img->image_bg_color = new Securimage_Color("#000000");
$img->text_color = new Securimage_Color("#FFFFFF");
$img->line_color = new Securimage_Color("#eeeeee");
$img->num_lines = 0;
$img->noise_level = 0;
$img->ttf_file = './custom-font.ttf';
$img->font_ratio = 0.5;
$img->charset = 'abcdefghkmnprstuvwyz23456789'; // exclude i,j,l,0,1,o
$img->code_length = '5';