#!/bin/bash

# start
if [ $1 = "start" ]; then

sudo systemctl start apache2
sudo systemctl start mysql
sudo systemctl start postgresql
mkdir -p /run/php/
sudo systemctl start php5.6-fpm
sudo systemctl start php7.0-fpm
sudo systemctl start php7.1-fpm
sudo systemctl start php7.2-fpm
sudo systemctl start php7.3-fpm
sudo systemctl start php7.4-fpm
sudo systemctl start php8.0-fpm
sudo systemctl start php8.1-fpm
sudo systemctl start php8.2-fpm
sudo systemctl start php8.3-fpm
sudo systemctl start php8.4-fpm
sudo systemctl start php8.5-fpm
echo "✅ successfully started lamp environment."

# restart
elif [ $1 = "restart" ]; then

sudo systemctl restart apache2
sudo systemctl restart mysql
sudo systemctl restart postgresql
mkdir -p /run/php/
sudo systemctl restart php5.6-fpm
sudo systemctl restart php7.0-fpm
sudo systemctl restart php7.1-fpm
sudo systemctl restart php7.2-fpm
sudo systemctl restart php7.3-fpm
sudo systemctl restart php7.4-fpm
sudo systemctl restart php8.0-fpm
sudo systemctl restart php8.1-fpm
sudo systemctl restart php8.2-fpm
sudo systemctl restart php8.3-fpm
sudo systemctl restart php8.4-fpm
sudo systemctl restart php8.5-fpm
echo "✅ successfully restarted lamp environment."

# stop
elif [ $1 = "stop" ]; then

sudo systemctl stop apache2
sudo systemctl stop mysql
killall -KILL mysqld >/dev/null 2>&1
killall -KILL mysqld >/dev/null 2>&1
killall -KILL mysqld >/dev/null 2>&1
killall -KILL mysqld >/dev/null 2>&1
sudo systemctl stop postgresql
sudo systemctl stop php5.6-fpm
sudo systemctl stop php7.0-fpm
sudo systemctl stop php7.1-fpm
sudo systemctl stop php7.2-fpm
sudo systemctl stop php7.3-fpm
sudo systemctl stop php7.4-fpm
sudo systemctl stop php8.0-fpm
sudo systemctl stop php8.1-fpm
sudo systemctl stop php8.2-fpm
sudo systemctl stop php8.3-fpm
sudo systemctl stop php8.4-fpm
sudo systemctl stop php8.5-fpm
echo "✅ successfully stopped lamp environment."

# add
elif [ $1 = "add" ]; then

PROJECT=$2
FILE="/etc/apache2/sites-available/$PROJECT.conf"

if [ -f $FILE ]; then
echo "⚠️ project $PROJECT already exists."
else  

if [ -n "$3" ]; then
PHP_LINE="
  <Proxy \"fcgi://localhost-stream/\" enablereuse=on flushpackets=on>
  </Proxy>
  <FilesMatch \.php$>
    <If \"%{HTTP:Accept} -strmatch '*text/event-stream*'\">
      SetHandler \"proxy:unix:/var/run/php/$3-fpm.sock|fcgi://localhost-stream/\"
      SetEnv no-gzip 1
      RequestHeader unset Accept-Encoding
    </If>
    <Else>
      SetHandler \"proxy:unix:/var/run/php/$3-fpm.sock|fcgi://localhost/\"
    </Else>
  </FilesMatch>
"
else
PHP_LINE=""
fi

if [ -n "$4" ]; then
FOLDER="$4"
else
FOLDER=$PROJECT
fi

DOMAIN="${PROJECT}.vielhuber.dev"
# special case for main domain
if [ "$PROJECT" = "vielhuber" ]; then
    DOMAIN="vielhuber.dev"
fi

if [[ "$5" == --port=* ]]; then
    PORT="${5#--port=}"
    PROXY_LINE="ProxyPreserveHost On
ProxyPass / http://$DOMAIN:$PORT/
ProxyPassReverse / http://$DOMAIN:$PORT/"
else
    PROXY_LINE=""
fi

if [[ "$5" == --alias=* ]]; then
    ALIAS="${5#--alias=}"
    ALIAS_LINE="ServerAlias $ALIAS www.$ALIAS"
else
    PROXY_LINE=""
fi

cat > $FILE << EOF
<VirtualHost *:80>
  ServerAdmin david@vielhuber.de
  ServerName $DOMAIN
  $ALIAS_LINE
  DocumentRoot /var/www/$FOLDER
  ErrorLog \${APACHE_LOG_DIR}/error.log
  CustomLog \${APACHE_LOG_DIR}/access.log combined
  <Directory /var/www>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
  $PHP_LINE
  $PROXY_LINE
</VirtualHost>
<VirtualHost *:443>
  ServerAdmin david@vielhuber.de
  ServerName $DOMAIN
  $ALIAS_LINE
  DocumentRoot /var/www/$FOLDER
  ErrorLog \${APACHE_LOG_DIR}/error.log
  CustomLog \${APACHE_LOG_DIR}/access.log combined
  <Directory /var/www>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
  $PHP_LINE
  SSLEngine on
  SSLCertificateFile /etc/letsencrypt/live/vielhuber.dev/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/vielhuber.dev/privkey.pem
</VirtualHost>
EOF
sudo a2ensite $PROJECT.conf
sudo systemctl reload apache2
#"/mnt/c/Users/David/apps/gsudo/gsudo.exe" -d "echo 127.0.0.1 $DOMAIN >> %windir%\System32\drivers\etc\hosts"
fi

# remove
elif [ $1 = "remove" ]; then

PROJECT=$2
FILE="/etc/apache2/sites-enabled/$PROJECT.conf"
if [ -f $FILE ]; then
rm $FILE
sudo a2dissite $PROJECT.conf
else
echo "⚠️ project $PROJECT does not exist."
fi
FILE="/etc/apache2/sites-available/$PROJECT.conf"
if [ -f $FILE ]; then
rm $FILE
fi
sudo systemctl reload apache2

else

echo "⚠️ unknown method."

fi