#!/bin/bash

# start
if [ $1 = "start" ]; then

sudo service apache2 start
sudo service mysql start
sudo service postgresql start
mkdir -p /run/php/
sudo service php5.6-fpm start
sudo service php7.0-fpm start
sudo service php7.1-fpm start
sudo service php7.2-fpm start
sudo service php7.3-fpm start
sudo service php7.4-fpm start
sudo service php8.0-fpm start
sudo service php8.1-fpm start
sudo service php8.2-fpm start
sudo service php8.3-fpm start

# restart
elif [ $1 = "restart" ]; then

sudo service apache2 restart
sudo service mysql restart
sudo service postgresql restart
mkdir -p /run/php/
sudo service php5.6-fpm restart
sudo service php7.0-fpm restart
sudo service php7.1-fpm restart
sudo service php7.2-fpm restart
sudo service php7.3-fpm restart
sudo service php7.4-fpm restart
sudo service php8.0-fpm restart
sudo service php8.1-fpm restart
sudo service php8.2-fpm restart
sudo service php8.3-fpm restart

# stop
elif [ $1 = "stop" ]; then

sudo service apache2 stop
sudo service mysql stop
killall -KILL mysqld
killall -KILL mysqld
killall -KILL mysqld
killall -KILL mysqld
sudo service postgresql stop
sudo service php5.6-fpm stop
sudo service php7.0-fpm stop
sudo service php7.1-fpm stop
sudo service php7.2-fpm stop
sudo service php7.3-fpm stop
sudo service php7.4-fpm stop
sudo service php8.0-fpm stop
sudo service php8.1-fpm stop
sudo service php8.2-fpm stop
sudo service php8.3-fpm stop

# add
elif [ $1 = "add" ]; then

PROJECT=$2
FILE="/etc/apache2/sites-available/$PROJECT.conf"

if [ -f $FILE ]; then
echo "Project $PROJECT already exists."
else  

if [ -n "$3" ]; then
PHP_LINE="<FilesMatch \.php$>
    SetHandler \"proxy:unix:/var/run/php/$3-fpm.sock|fcgi://localhost/\"
</FilesMatch>"
else
PHP_LINE=""
fi

if [ -n "$4" ]; then
FOLDER="$4"
else
FOLDER=$PROJECT
fi

if [ -n "$5" ]; then
PROXY_LINE="ProxyPreserveHost On
ProxyPass / http://$PROJECT.local.vielhuber.de:$5/
ProxyPassReverse / http://$PROJECT.local.vielhuber.de:$5/"
else
PROXY_LINE=""
fi

cat > $FILE << EOF
<VirtualHost *:80>
  ServerAdmin david@vielhuber.de
  ServerName $PROJECT.local.vielhuber.de
  DocumentRoot /var/www/$FOLDER
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
  <Directory /var/www>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
  $PHP_LINE
  $PROXY_LINE
</VirtualHost>
<VirtualHost *:443>
  ServerAdmin david@vielhuber.de
  ServerName $PROJECT.local.vielhuber.de
  DocumentRoot /var/www/$FOLDER
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
  <Directory /var/www>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
  $PHP_LINE
  SSLEngine on
  SSLCertificateFile /var/www/lamp/ssl.cert
  SSLCertificateKeyFile /var/www/lamp/ssl.key
</VirtualHost>
EOF
sudo a2ensite $PROJECT.conf
sudo service apache2 reload
#"/mnt/c/Users/David/apps/gsudo/gsudo.exe" -d "echo 127.0.0.1 $PROJECT.local.vielhuber.de >> %windir%\System32\drivers\etc\hosts"
fi

# remove
elif [ $1 = "remove" ]; then

PROJECT=$2
FILE="/etc/apache2/sites-available/$PROJECT.conf"
if [ -f $FILE ]; then
rm $FILE
sudo a2dissite $PROJECT.conf
sudo service apache2 reload
else
echo "Project $PROJECT does not exist."
fi

else

echo "unknown method"

fi