WITH RECURSIVE r(i) AS (
  VALUES(0)
  UNION ALL
  SELECT i FROM r
  LIMIT 10000000
)
INSERT INTO test (col1, col2, col3) VALUES ((SELECT i FROM r ORDER BY i LIMIT 1), (SELECT i FROM r ORDER BY i LIMIT 1), (SELECT i FROM r ORDER BY i LIMIT 1));
