#!/bin/sh
qread="/var/qmail/bin/qmail-qread"
len=`$qread | wc -l`
if [ $len -gt 500 ]; then
#!/bin/bash
# script to send simple email
# email subject
SUBJECT="WARNING: There are $len messages in the mail queue!"
# Email To ?
EMAIL="mail@cornelia-sell.com,david@vielhuber.de"
# Email text/message
EMAILMESSAGE="/var/tmp/qmail.txt"
echo "WARNING: There are $len messages in the mail queue!" > $EMAILMESSAGE
/var/qmail/bin/qmail-qstat >> $EMAILMESSAGE
/var/qmail/bin/qmail-qread >> $EMAILMESSAGE
echo "> This is a chkmailq script..." >> $EMAILMESSAGE
# send an email using /bin/mail

   if ps ax | grep -v grep | grep 'qmail-clean' > /dev/null
   then
      mail -s "$SUBJECT" "$EMAIL" < $EMAILMESSAGE
      /etc/init.d/qmail stop
   else
      echo "qmail is not running"
   fi

fi
