name: CI

env:
    CI: true
    SECRET_VARIABLE_1: ${{ secrets.SECRET_VARIABLE_1 }}
    SECRET_VARIABLE_2: ${{ secrets.SECRET_VARIABLE_2 }}
    SECRET_VARIABLE_3: ${{ secrets.SECRET_VARIABLE_3 }}

on:
    # on manual push
    workflow_dispatch:
    # on push general
    #push:
    # on push to tags
    push:
        tags:
            - 'v*'
            - '[0-9]*'

jobs:
    build-test:
        strategy:
            max-parallel: 9
            fail-fast: true
            matrix:
                operating-system: ['ubuntu-22.04', 'macos-latest', 'windows-latest'] # don't use "ubuntu-latest" here, since act maps that to ubuntu-20
                php-versions: ['8.3', '8.4', '8.5']
                node-versions: ['lts/*']

        timeout-minutes: 15

        runs-on: ${{ matrix.operating-system }}

        name: ${{ matrix.operating-system }} (PHP ${{ matrix.php-versions }}, Node ${{ matrix.node-versions }})

        permissions:
            contents: read
            packages: write

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: root
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                  lfs: true

            - name: Install libraries
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                  	   sudo apt-get update
                       sudo apt-get install -y coreutils nano
                       sudo apt-get install -y libsodium23 libzip-dev libc-client-dev libkrb5-dev
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                       brew install coreutils
                  elif [ "$RUNNER_OS" == "Windows" ]; then
                       choco install busybox -y
                  fi
              shell: bash

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-versions }}'
                  extensions: fileinfo, mysqli, pdo_mysql, pdo_sqlite, xdebug, mbstring, gd, intl, xml, zip, soap, bcmath, imap, opcache, pgsql, pdo, imagick
                  tools: composer, phpunit

            - name: Install MySQL
              uses: shogo82148/actions-setup-mysql@v1
              with:
                  mysql-version: '8.0'
            	  # use "127.0.0.1" as host and "root" as username
                  root-password: 'root'
                  
            - name: Install Composer
              working-directory: .
              run: composer update && composer install --no-interaction

            - name: Install Node
              uses: actions/setup-node@v6
              with:
                  node-version: '${{ matrix.node-versions }}'

            - name: Install NPM
              working-directory: .
              run: npm install

            - name: Create .env file if needed
              if: false
              run: |
                  cat > .env << EOF
                  SECRET_VARIABLE_1=${{ secrets.SECRET_VARIABLE_1 }}
                  SECRET_VARIABLE_2=${{ secrets.SECRET_VARIABLE_2 }}
                  SECRET_VARIABLE_3=${{ secrets.SECRET_VARIABLE_3 }}
                  EOF
              shell: bash

            - name: Start PHP Server
              if: false
              run: php -S localhost:8000 -t . > /tmp/php-server.log 2>&1 &
              shell: bash

            - name: PHP Tests
              if: false
              working-directory: .
              run: ./vendor/bin/phpunit

            - name: JS Tests
              if: false
              working-directory: .
              run: npm run js:tests
			  
            - name: Docker build - Login
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker build - Push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ghcr.io/vielhuber/custom:latest