name: CI

env:
    CI: true
    SECRET_VARIABLE_1: ${{ secrets.SECRET_VARIABLE_1 }}
    SECRET_VARIABLE_2: ${{ secrets.SECRET_VARIABLE_2 }}
    SECRET_VARIABLE_3: ${{ secrets.SECRET_VARIABLE_3 }}

on:
    # on manual push
    workflow_dispatch:
    # on push general
    #push:
    # on push to tags
    push:
        tags:
            - 'v*'
            - '[0-9]*'

jobs:
    build-test:
        strategy:
            max-parallel: 9
            fail-fast: true
            matrix:
                operating-system: ['ubuntu-latest', 'macos-latest', 'windows-latest']
                php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3']
                node-versions: ['lts/*']

		timeout-minutes: 15

        runs-on: ${{ matrix.operating-system }}

        name: ${{ matrix.operating-system }} (PHP ${{ matrix.php-versions }}, Node ${{ matrix.node-versions }})

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: root
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install libraries
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                  	   sudo apt-get update
                       sudo apt-get install -y coreutils
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                       brew install coreutils
                  elif [ "$RUNNER_OS" == "Windows" ]; then
                       choco install busybox -y
                  fi
              shell: bash

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-versions }}'
                  extensions: fileinfo, mysqli, pdo_mysql, xdebug, mbstring, xmlrpc, gd, intl, xml, zip, soap, bcmath, imap, opcache, pgsql, pdo, imagick
                  tools: composer, phpunit

            # use 127.0.0.1 as host
            - name: Install MySQL
              uses: shogo82148/actions-setup-mysql@v1
              with:
                  mysql-version: '8.0'
                  root-password: 'root'
                  
            - name: Install Composer
              run: composer install --no-interaction

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: '${{ matrix.node-versions }}'

            - name: Install NPM
              run: npm install

            - name: Create .env file if needed
              run: |
                  cat > .env << EOF
                  SECRET_VARIABLE_1=${{ secrets.SECRET_VARIABLE_1 }}
                  SECRET_VARIABLE_2=${{ secrets.SECRET_VARIABLE_2 }}
                  SECRET_VARIABLE_3=${{ secrets.SECRET_VARIABLE_3 }}
                  EOF
              shell: bash

            - name: Start PHP Server
              run: php -S localhost:8000 -t path/to/vhost > /tmp/php-server.log 2>&1 &
              shell: bash

            - name: PHP Tests
              run: ./vendor/bin/phpunit

            - name: JS Tests
              run: npm run js:tests
